# name: ci_practice

# on: 
#   push:
#     branches:
#       - develop
#   pull_request:
#     branches:
#       - develop

# jobs:
#   Install_dependencies:
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: actions/checkout@v2
#       - name: cache dependencies
#         uses: actions/cache@v1
#         with:
#           path: ~/.npm
#           key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
#           restore-keys: |
#             ${{runner.os}}-node-
#       - name: set-up node
#         uses: actions/setup-node@v1
#         with:
#           node-version: '16.*'
#       - name: Install dependencies
#         run: npm ci 
#       - name: Build_project
#         if: ${{github.event_name}} == 'push'
#         run: npm run build